services:
  - type: web
    name: doclink-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
