import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import * as Lucide from "lucide-react";
import { jsPDF } from "jspdf";
import { Link } from "react-router-dom";
import { fetchMyPrescriptions } from "../../api/prescriptions";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Skeleton } from "../../components/ui/Skeleton";

const PrescriptionCard = ({ rx }) => {
  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.text("DocLink - Medical Prescription", 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Date: ${rx.date}`, 150, 20);
    
    doc.line(20, 25, 190, 25);
    
    // Doctor Info
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(rx.doctorName, 20, 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(rx.specialty, 20, 47);
    
    // Diagnosis
    doc.setFont("helvetica", "bold");
    doc.text("Diagnosis:", 20, 60);
    doc.setFont("helvetica", "normal");
    doc.text(rx.diagnosis, 45, 60);
    
    // Medicines
    doc.setFont("helvetica", "bold");
    doc.text("Medicines:", 20, 75);
    
    let y = 85;
    rx.medicines.forEach((med, index) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${index + 1}. ${med.name}`, 25, y);
      doc.setFont("helvetica", "normal");
      doc.text(`${med.dosage} - ${med.frequency} for ${med.duration}`, 30, y + 7);
      y += 15;
    });
    
    // Notes
    doc.setFont("helvetica", "bold");
    doc.text("Doctor's Notes:", 20, y + 10);
    doc.setFont("helvetica", "italic");
    doc.text(rx.notes, 20, y + 17);
    
    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Generated by DocLink Telemedicine Portal", 20, 280);
    
    doc.save(`DocLink_Prescription_${rx.doctorName.replace(/\s+/g, '_')}_${rx.date.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="bg-white/5 border border-white/10 rounded-2xl overflow-hidden shadow-xl"
    >
      <div className="p-8">
        <div className="flex justify-between items-start mb-6">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-cyan-500/10 text-cyan-400 rounded-xl flex items-center justify-center text-3xl font-serif italic font-bold">
              Rx
            </div>
            <div>
              <h3 className="text-white font-bold text-lg uppercase tracking-wider">Prescription</h3>
              <p className="text-gray-500 text-sm">Case #{rx.id}</p>
            </div>
          </div>
          <p className="text-gray-400 text-sm font-medium">{rx.date}</p>
        </div>

        <div className="flex flex-wrap items-center gap-x-8 gap-y-4 mb-8 p-4 bg-white/5 rounded-xl border border-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white font-bold shrink-0">
              {rx.doctorInitials || "DR"}
            </div>
            <div>
              <p className="text-white text-sm font-semibold">{rx.doctorName}</p>
              <p className="text-gray-500 text-xs">{rx.specialty}</p>
            </div>
          </div>
          <div className="h-8 w-px bg-white/10 hidden md:block" />
          <div className="space-y-1">
            <p className="text-xs text-gray-500 uppercase tracking-widest">Diagnosis</p>
            <Badge className="bg-amber-500/10 text-amber-500 border-amber-500/20 py-0.5">
              {rx.diagnosis}
            </Badge>
          </div>
        </div>

        <div className="space-y-4 mb-8">
          <h4 className="text-white font-semibold text-sm flex items-center gap-2">
            <Lucide.Pill className="w-4 h-4 text-cyan-400" />
            Medicines & Dosage
          </h4>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-white/5 text-gray-500">
                  <th className="pb-3 font-medium">Medicine</th>
                  <th className="pb-3 font-medium text-center">Dosage</th>
                  <th className="pb-3 font-medium text-center">Frequency</th>
                  <th className="pb-3 font-medium text-right">Duration</th>
                </tr>
              </thead>
              <tbody>
                {rx.medicines.map((med, idx) => (
                  <tr key={idx} className="border-b border-white/5 last:border-0">
                    <td className="py-4 font-semibold text-white">{med.name}</td>
                    <td className="py-4 text-gray-400 text-center">{med.dosage}</td>
                    <td className="py-4 text-gray-400 text-center">{med.frequency}</td>
                    <td className="py-4 text-gray-400 text-right">{med.duration}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="bg-white/5 rounded-xl p-4 border-l-2 border-cyan-500/30 mb-8">
          <p className="text-xs text-gray-500 uppercase tracking-widest mb-1">Doctor's Notes</p>
          <p className="text-gray-300 text-sm italic">"{rx.notes}"</p>
        </div>

        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-6 border-t border-white/10">
          <div className="flex items-center gap-2">
            {rx.valid ? (
              <Badge className="bg-green-500/10 text-green-400 border-green-500/20 flex items-center gap-1.5 px-3">
                <div className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                Valid Prescription
              </Badge>
            ) : (
              <Badge className="bg-gray-500/10 text-gray-400 border-gray-500/20 px-3">
                Expired
              </Badge>
            )}
            <span className="text-gray-600 text-xs tracking-tighter">Verified by DocLink HealthID</span>
          </div>
          
          <Button 
            onClick={downloadPDF}
            className="bg-white text-black hover:bg-gray-200 border-none px-6 py-2 h-auto text-sm font-bold flex items-center gap-2 active:scale-95 transition-all shadow-xl shadow-white/5"
          >
            <Lucide.Download className="w-4 h-4" />
            Download PDF
          </Button>
        </div>
      </div>
    </motion.div>
  );
};

const PatientPrescriptions = () => {
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        const data = await fetchMyPrescriptions();
        setPrescriptions(data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, []);

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold text-white mb-1">My Prescriptions</h2>
        <p className="text-gray-500">Access and download your digital prescriptions.</p>
      </div>

      <div className="grid grid-cols-1 gap-8">
        {loading ? (
          [...Array(3)].map((_, i) => (
            <Skeleton key={i} className="h-[400px] w-full rounded-2xl" />
          ))
        ) : error ? (
          <div className="flex flex-col items-center justify-center py-20 text-center bg-white/5 border border-white/10 rounded-2xl">
            <Lucide.AlertCircle className="w-10 h-10 text-red-500 mb-4" />
            <p className="text-text-secondary">Failed to load prescriptions.</p>
          </div>
        ) : prescriptions.length > 0 ? (
          prescriptions.map((rx) => (
            <PrescriptionCard key={rx.id} rx={rx} />
          ))
        ) : (
          <div className="flex flex-col items-center justify-center py-20 text-center bg-white/5 border border-white/10 rounded-2xl">
            <div className="w-20 h-20 rounded-full bg-white/5 flex items-center justify-center mb-6">
              <Lucide.FileX className="w-10 h-10 text-gray-600" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">No Prescriptions Yet</h3>
            <p className="text-gray-500 max-w-sm mb-6">
              Your digital prescriptions will appear here once your consultations are complete.
            </p>
            <Button className="bg-cyan-500 hover:bg-cyan-600 text-white" asChild>
              <Link to="/doctors">Find a Doctor</Link>
            </Button>
          </div>
        )}
      </div>
    </div>
  );
};

export default PatientPrescriptions;
